// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TayDuKyAPI.Models;

namespace TayDuKyAPI.Migrations
{
    [DbContext(typeof(PRM391Context))]
    partial class PRM391ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TayDuKyAPI.Models.ActorRole", b =>
                {
                    b.Property<int>("ActorRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ActorRoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActorInScenario");

                    b.Property<string>("ActorRoleDescription");

                    b.Property<int?>("Admin");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RoleScenarioId")
                        .HasColumnName("RoleScenarioID");

                    b.Property<int?>("ScenarioId");

                    b.HasKey("ActorRoleId");

                    b.HasIndex("ActorInScenario");

                    b.HasIndex("RoleScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ActorRole");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EquipmentID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquipmentDes")
                        .HasMaxLength(50);

                    b.Property<string>("EquipmentImage")
                        .HasMaxLength(100);

                    b.Property<int?>("EquipmentIsDelete");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("EquipmentQuantity");

                    b.Property<int?>("EquipmentStatus");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.EquipmentInScenario", b =>
                {
                    b.Property<int>("EquipInScenario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EquipmentId")
                        .HasColumnName("EquipmentID");

                    b.Property<int?>("EquipmentQuantity");

                    b.Property<int?>("ScenarioId")
                        .HasColumnName("ScenarioID");

                    b.HasKey("EquipInScenario");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("EquipmentInScenario");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.RoleScenario", b =>
                {
                    b.Property<int>("RoleScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleScenarioID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleScenarioName")
                        .HasMaxLength(50);

                    b.HasKey("RoleScenarioId");

                    b.ToTable("RoleScenario");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.Scenario", b =>
                {
                    b.Property<int>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ScenarioID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ScenarioCastAmout");

                    b.Property<string>("ScenarioDes")
                        .HasMaxLength(255);

                    b.Property<string>("ScenarioLocation")
                        .HasMaxLength(50);

                    b.Property<string>("ScenarioName")
                        .HasMaxLength(50);

                    b.Property<int?>("ScenarioStatus");

                    b.Property<DateTime?>("ScenarioTimeFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ScenarioTimeTo")
                        .HasColumnType("datetime");

                    b.HasKey("ScenarioId");

                    b.ToTable("Scenario");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserAdress")
                        .HasMaxLength(100);

                    b.Property<string>("UserDescription")
                        .HasMaxLength(255);

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserImage")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserPhoneNum")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("UserRole");

                    b.Property<int>("UserStatus");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.ActorRole", b =>
                {
                    b.HasOne("TayDuKyAPI.Models.User", "ActorInScenarioNavigation")
                        .WithMany("ActorRoles")
                        .HasForeignKey("ActorInScenario")
                        .HasConstraintName("FK_ActorRole_User");

                    b.HasOne("TayDuKyAPI.Models.RoleScenario", "RoleScenario")
                        .WithMany("ActorRoles")
                        .HasForeignKey("RoleScenarioId")
                        .HasConstraintName("FK_ActorRole_RoleScenarios");

                    b.HasOne("TayDuKyAPI.Models.Scenario", "Scenario")
                        .WithMany("ActorRoles")
                        .HasForeignKey("ScenarioId")
                        .HasConstraintName("FK_ActorRole_Scenario");
                });

            modelBuilder.Entity("TayDuKyAPI.Models.EquipmentInScenario", b =>
                {
                    b.HasOne("TayDuKyAPI.Models.Equipment", "Equipment")
                        .WithMany("EquipmentInScenarios")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK_EquipmentInScenario_Equipment");

                    b.HasOne("TayDuKyAPI.Models.Scenario", "Scenario")
                        .WithMany("EquipmentInScenarios")
                        .HasForeignKey("ScenarioId")
                        .HasConstraintName("FK_EquipmentInScenario_Scenario");
                });
#pragma warning restore 612, 618
        }
    }
}
